### PR TITLE
[WIP]Shushman/1.0 fixes

### PR DESCRIPTION
**Pull request by Shushman**
2 things for you @zsunberg (in particular):
- Check in `src/transitions.jl` that my redefinition of `Base.iterate` is correct
- Tests fail because `POMDPModels` cannot be found (even though it is `add`ed). I'm guessing this will be sorted out once the registry thing works?

### CODE REVIEW

**Comment by Shushman** [comment]
Okay I've been wading through test errors to now arrive at one I just don't know how or where to fix:
```
ERROR: LoadError: ArgumentError: Sampler for this object is not defined
Stacktrace:
 [1] Random.Sampler(::Type{MersenneTwister}, ::Random.SamplerTrivial{LaserTag.LTInitialBelief,Any}, ::Val{1}) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Random/src/Random.jl:134
 [2] Random.Sampler(::MersenneTwister, ::Random.SamplerTrivial{LaserTag.LTInitialBelief,Any}, ::Val{1}) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Random/src/Random.jl:131
 [3] rand(::MersenneTwister, ::Random.SamplerTrivial{LaserTag.LTInitialBelief,Any}) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Random/src/Random.jl:221 (repeats 2 times)
 [4] get_initialstate(::HistoryRecorder, ::LaserTag.LTInitialBelief) at /Users/shushmanchoudhury/.julia/packages/POMDPSimulators/oXnp0/src/history_recorder.jl:256
 [5] simulate(::HistoryRecorder, ::LaserTagPOMDP{DESPOTEmu,StaticArrays.MArray{Tuple{8},Int64,1,8}}, ::RandomPolicy{MersenneTwister,LaserTagPOMDP{DESPOTEmu,StaticArrays.MArray{Tuple{8},Int64,1,8}},BeliefUpdaters.NothingUpdater}, ::SimpleParticleFilter{LTState,LaserTagPOMDP{DESPOTEmu,StaticArrays.MArray{Tuple{8},Int64,1,8}},LowVarianceResampler,MersenneTwister}, ::LaserTag.LTInitialBelief) at /Users/shushmanchoudhury/.julia/packages/POMDPSimulators/oXnp0/src/history_recorder.jl:90
 [6] simulate(::HistoryRecorder, ::LaserTagPOMDP{DESPOTEmu,StaticArrays.MArray{Tuple{8},Int64,1,8}}, ::RandomPolicy{MersenneTwister,LaserTagPOMDP{DESPOTEmu,StaticArrays.MArray{Tuple{8},Int64,1,8}},BeliefUpdaters.NothingUpdater}, ::SimpleParticleFilter{LTState,LaserTagPOMDP{DESPOTEmu,StaticArrays.MArray{Tuple{8},Int64,1,8}},LowVarianceResampler,MersenneTwister}) at /Users/shushmanchoudhury/.julia/packages/POMDPSimulators/oXnp0/src/history_recorder.jl:64
 [7] top-level scope at none:0
 [8] include at ./boot.jl:317 [inlined]
 [9] include_relative(::Module, ::String) at ./loading.jl:1038
 [10] include(::Module, ::String) at ./sysimg.jl:29
 [11] include(::String) at ./client.jl:388
 [12] top-level scope at none:0
in expression starting at /Users/shushmanchoudhury/.julia/dev/LaserTag/test/runtests.jl:19
ERROR: Package LaserTag errored during testing
```

**Comment by Shushman** [comment]
Tests don't throw any more errors but also seem to take forever to run. Can you test them @zsunberg ?

**Comment by zsunberg** [comment]
Yeah, I'll look at it soon! Thanks for all the work!!

**Comment by zsunberg** [comment]
@Shushman the reason it took forever to run was because of the deprecation errors. Every time it created an MVector, it had to check whether that deprecation error had been thrown already. Fixed now.

**Pull request merged**
